import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0D0D0D",
    paddingTop: 72,
  },
  formContainer: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 24,
    marginTop: 40,
    marginHorizontal: 24,
  },
  formInput: {
    backgroundColor: "#262626",
    color: "#F2F2F2",
    padding: 16,
    paddingRight: 0,
    fontSize: 16,
    borderWidth: 1,
    borderRadius: 6,
    flex: 1,
  },
  formButton: {
    width: 58,
    height: 58,
    padding: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1E6F9F",
    borderRadius: 6,
  },
  tasksContainer: {
    flex: 1,
    width: "100%",
    backgroundColor: "#1A1A1A",
    marginTop: -32,
    paddingHorizontal: 24,
    zIndex: -1,
  },
  infoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 64,
  },
  infoBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoText: {
    fontSize: 14,
    fontWeight: "bold",
  },
  infoNumber: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontWeight: "bold",
    fontSize: 12,
    backgroundColor: "#333333",
    color: "#D9D9D9",
    borderRadius: 9999,
  },
  tasksList: {
    alignItems: "center",
    gap: 16,
    paddingVertical: 48,
    marginTop: 20,
    borderTopWidth: 1,
    borderColor: "#333333",
  },
  emptyTasksListText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#808080",
  },
})
